dw_user_homepage:
    pattern:  /hello
    defaults: { _controller: DWUserBundle:Default:index }
    
dw_password_reinit:
    pattern:  /pass/{email}
    defaults: { _controller: DWUserBundle:Default:passwordReinit }
    
dw_password_reinit_post:
    pattern:  /pass/reinit
    defaults: { _controller: DWUserBundle:Default:passwordReinitPost }
    

