dw_user_homepage:
    pattern:  /hello
    defaults: { _controller: DWUserBundle:Default:index }
    
dw_password_reinit:
    pattern:  /pass/{email}
    defaults: { _controller: DWUserBundle:Default:passwordReinit }
    
dw_password_reinit_post:
    pattern:  /pass/reinit
    defaults: { _controller: DWUserBundle:Default:passwordReinitPost }
    
dw_user_login:
    pattern:  /login
    defaults: { _controller: DWUserBundle:Default:login }
    
dw_user_role:
    resource: "@DWUserBundle/Resources/config/routing/role.yml"
    prefix:   /role
    
dw_user:
    resource: "@DWUserBundle/Resources/config/routing/user.yml"
    prefix:   /user
    

